export const SET_CURRENT_PATH = 'SET_CURRENT_PATH';

export const GET_FOLDER_CONTENTS_FAILURE = 'GET_FOLDER_CONTENTS_FAILURE';
export const GET_FOLDER_CONTENTS_SUCCESS = 'GET_FOLDER_CONTENTS_SUCCESS';
