export const SET_CURRENT_PATH_REQUEST = 'SET_CURRENT_PATH_REQUEST';
export const SET_CURRENT_PATH_FAILURE = 'SET_CURRENT_PATH_FAILURE';
export const SET_CURRENT_PATH_SUCCESS = 'SET_CURRENT_PATH_SUCCESS';
